[application]
name = "ttrpg-assistant-frontend"
default_platform = "web"

[web.app]
title = "TTRPG Assistant"
base_path = "/"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]
port = 3030

[web.resource]
style = []
script = []

[web.resource.dev]
style = []
script = []
